// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/vadimpk/ppc-project/entity"
)

// BusinessServiceRepository is an autogenerated mock type for the BusinessServiceRepository type
type BusinessServiceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, service
func (_m *BusinessServiceRepository) Create(ctx context.Context, service *entity.BusinessService) error {
	ret := _m.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.BusinessService) error); ok {
		r0 = rf(ctx, service)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BusinessServiceRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *BusinessServiceRepository) Get(ctx context.Context, id int) (*entity.BusinessService, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.BusinessService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*entity.BusinessService, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.BusinessService); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BusinessService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, businessID
func (_m *BusinessServiceRepository) List(ctx context.Context, businessID int) ([]entity.BusinessService, error) {
	ret := _m.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.BusinessService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.BusinessService, error)); ok {
		return rf(ctx, businessID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.BusinessService); ok {
		r0 = rf(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BusinessService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListActive provides a mock function with given fields: ctx, businessID
func (_m *BusinessServiceRepository) ListActive(ctx context.Context, businessID int) ([]entity.BusinessService, error) {
	ret := _m.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []entity.BusinessService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.BusinessService, error)); ok {
		return rf(ctx, businessID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.BusinessService); ok {
		r0 = rf(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BusinessService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, service
func (_m *BusinessServiceRepository) Update(ctx context.Context, service *entity.BusinessService) error {
	ret := _m.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.BusinessService) error); ok {
		r0 = rf(ctx, service)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBusinessServiceRepository creates a new instance of BusinessServiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBusinessServiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BusinessServiceRepository {
	mock := &BusinessServiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
