version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    container_name: ppc_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ppc
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
